### ISSUE TITLE
슬기 버그 메뉴 버그

### ISSUE THREAD

**Issue by astroluj** [KMUGradeServerProject/KMUGradeServerProject#199]
슬기 버그 내 우측 컴퓨터에서 메인화면 가는 버튼 이상하게 나옴
슬기 메인 공지 버그 내우측 컴퓨터에서 화살표 잘려서 나옴
슬기 차트 버그 내 우측 컴퓨터에서 차트 안나옴

**Comment by cs09g** [comment]
IE 8에서 발생하는 에러

**Comment by cs09g** [comment]
차트 크기는 % 대신 수치를 직접 할당.

**Comment by cs09g** [comment]
Navigation bar에 Logo옆 글자는 공간을 늘려주어서 해결, 차트는 비율로 적용 되어있던 width를 특정 수치를 주어 고정하였음.
