### ISSUE TITLE
과제 등록 버그

### ISSUE THREAD

**Issue by dollking** [KMUGradeServerProject/KMUGradeServerProject#207]
사용자 등록 후 문제 추가 등록 시 학생 폴더 생성되지 않음

**Comment by cs09g** [comment]
현재 학생 폴더는 과목 관리자가 학생을 자신의 과목에 등록했을때 생성하고 있음.
이럴 경우, 학생을 추가한 이후에 문제를 새로 등록하게되면 싱크가 맞지 않게 됨.
(폴더의 구조 : 'CurrentCourses - 과목 - 문제 - 유저' 이므로 문제 - 유저 순으로 등록해야만 함)
그렇기 때문에 차라리 학생이 어느 문제에 대해 코드를 제출하게 되면 그 때 폴더를 생성하는 것이 나아 보임.

**Comment by cs09g** [comment]
과목의 운영 기간이 끝난 후 사용자에게 코드를 제공하기 위한 경로 생성의 편의를 위해
CurrentCourses - 과목 - 문제 - 유저 의 경로를
CurrentCourses - 과목 - 유저 - 문제 경로로 변경함.
과목 담당자가 어느 과목에 유저를 등록하게 되면 Current Courses - 과목 - 유저 경로를 생성함.
이 후의 문제 폴더는 사용자가 문제에 대한 코드를 제출하면 생성됨.
