### ISSUE TITLE
마스터, 과목 관리자 문제 추가가 안됨 ㅠ.

### ISSUE THREAD

**Issue by astroluj** [KMUGradeServerProject/KMUGradeServerProject#320]
이유를 모르겠음

**Comment by astroluj** [comment]
과목이 -> 과목 관리 -> 문제 -> ADD -> 선택 선택 작업후 날짜 정하고 돈 누르면 에러! 알수 없는 에러!!
마스터이 ->서버 관리 ->문제 ->> ADD -> 파일 선택 (낱개던 여러개던 노상관) -> 확인! 에러! 알수 없는 에러!

**Comment by cs09g** [comment]
tmp 폴더가 비어있지 않을 때 발생하는 에러. 예외처리 추가함.
