### ISSUE TITLE
showing language choices

### ISSUE THREAD

**Issue by cs09g** [KMUGradeServerProject/KMUGradeServerProject#43]
1. Showing up languages on problem pages up to course information on database. - enhancement 
(upload files / write code both)

2. Python shows '*.py' file type can upload, but other languages shows 'Custom files' - question

3. Can you remove 'All files' option? - question

**Comment by LLljs** [comment]
1. complete
2. need to search
3. need to search

**Comment by LLljs** [comment]
2. chrome or firefox browser's quality
3. no need to remove 'All files'
