### ISSUE TITLE
텍스트 Input Form 정렬

### ISSUE THREAD

**Issue by astroluj** [KMUGradeServerProject/KMUGradeServerProject#472]
텍스트 Input Form 형태 정렬 
기준 잡아서 정렬 시행 하도록

**Comment by cs09g** [comment]
edit_personal의 경우에는 화면 크기가 작아지면 form이 가로 길이에 맞게 늘어나게 되는데, 이때에는 form이름이 왼쪽 정렬되어있는게 가독성이 더 좋음. 그래서 가운데 정렬안해도 괜찮을 듯.
