### ISSUE TITLE
과목관리자가 개인으로 학생 추가할 때 안됨.

### ISSUE THREAD

**Issue by astroluj** [KMUGradeServerProject/KMUGradeServerProject#481]
한 번 에러나니까 동작도 안되고.
유저 값넣고 닫았다가 다시 키면 DisAbled -> Enabled로 바뀜

**Comment by cs09g** [comment]
IE에서 발생하는 듯.

**Comment by cs09g** [comment]
1. option의 값을 split으로 잘라서 index를 얻은 후에 그대로 사용하였는데, 이럴 경우 대학/학부가 폐지되었을 경우 화면에 나타나는 대학/학부의 index 값과 option으로서의 index가 일치하지 않아서 문제 발생.
2. split(' ')로 잘라서 인덱스를 얻었는데, IE에서는 값 사이에 스페이스가 없다고 인식하였음. split대신에 match함수를 사용하여 정수값을 추출해 index로 사용하였음.

**Comment by cs09g** [comment]
IE10 이하에서 재검사 필요.

**Comment by cs09g** [comment]
브라우저의 최신버전에서만 동작하도록 처리
