### ISSUE TITLE
Can't add new user with Internet explorer

### ISSUE THREAD

**Issue by dollking** [KMUGradeServerProject/KMUGradeServerProject#82]
Web page's design printed in monitor is different from the chrome/firefox and IE.
For example, result of adding user, and chart's size and position, etc.

**Comment by cs09g** [comment]
under IE8 doesn't allow to use HTML5-canvas

**Comment by cs09g** [comment]
submit button outside of 'form' tag was not working in IE, So, move the button inside of 'form' tag and give a id. and used JavaScript for submit. It's solved. document.getElementById('form id here').submit().
